from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class SampleDoc:
    filename: str
    title: str
    pages: int


SAMPLE_DOCS: list[SampleDoc] = [
    SampleDoc("01.Sample_ID.pdf", "Sample ID Document", 2),
    SampleDoc("02.Sample_Certificate.pdf", "Sample Certificate", 1),
    SampleDoc("03.Sample_Proof_of_Address.pdf", "Sample Proof of Address", 2),
    SampleDoc("04.Sample_Employment_Letter.pdf", "Sample Employment Letter", 1),
    SampleDoc("05.Sample_Payslips.pdf", "Sample Payslips", 3),
]


def _pdf_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def _build_minimal_pdf(title: str, pages: int) -> bytes:
    # Minimal PDF generator (no external deps). Produces Type1 Helvetica text on A4-ish pages.
    objects: list[bytes] = []

    def add_obj(body: bytes) -> int:
        objects.append(body)
        return len(objects)

    def text_stream(lines: list[tuple[int, int, int, str]]) -> bytes:
        parts: list[str] = ["BT"]
        for font_size, x, y, text in lines:
            parts.append(f"/F1 {font_size} Tf {x} {y} Td ({_pdf_escape(text)}) Tj")
        parts.append("ET")
        stream = "\n".join(parts).encode("ascii")
        return stream

    # 1: Catalog, 2: Pages, 3..: Page + Contents per page, plus Font resource.
    catalog_id = add_obj(b"<< /Type /Catalog /Pages 2 0 R >>")

    # Placeholder Pages object, filled later once page object ids are known.
    pages_placeholder_id = add_obj(b"<< /Type /Pages /Kids [] /Count 0 >>")

    font_id = add_obj(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")

    page_ids: list[int] = []

    for i in range(pages):
        lines = [
            (18, 72, 760, title),
            (12, 0, -28, "SAMPLE ONLY - NO REAL DATA"),
            (12, 0, -20, f"Page {i + 1} of {pages}"),
            (10, 0, -640, "Generated by scripts/generate_sample_pdfs.py"),
        ]
        stream = text_stream(lines)
        contents_id = add_obj(
            b"<< /Length "
            + str(len(stream)).encode("ascii")
            + b" >>\nstream\n"
            + stream
            + b"\nendstream"
        )

        page_id = add_obj(
            b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] "
            b"/Resources << /Font << /F1 "
            + str(font_id).encode("ascii")
            + b" 0 R >> >> "
            b"/Contents "
            + str(contents_id).encode("ascii")
            + b" 0 R >>"
        )
        page_ids.append(page_id)

    kids = b"[ " + b" ".join(f"{pid} 0 R".encode("ascii") for pid in page_ids) + b" ]"
    pages_obj = b"<< /Type /Pages /Kids " + kids + b" /Count " + str(pages).encode("ascii") + b" >>"
    objects[pages_placeholder_id - 1] = pages_obj

    # Build final PDF with xref.
    header = b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n"
    out = bytearray(header)
    offsets: list[int] = [0]

    for i, obj in enumerate(objects, start=1):
        offsets.append(len(out))
        out.extend(f"{i} 0 obj\n".encode("ascii"))
        out.extend(obj)
        out.extend(b"\nendobj\n")

    xref_start = len(out)
    out.extend(f"xref\n0 {len(objects) + 1}\n".encode("ascii"))
    out.extend(b"0000000000 65535 f \n")
    for off in offsets[1:]:
        out.extend(f"{off:010d} 00000 n \n".encode("ascii"))

    out.extend(
        b"trailer\n<< /Size "
        + str(len(objects) + 1).encode("ascii")
        + b" /Root "
        + str(catalog_id).encode("ascii")
        + b" 0 R >>\nstartxref\n"
        + str(xref_start).encode("ascii")
        + b"\n%%EOF\n"
    )
    return bytes(out)


def generate_pdf(path: Path, title: str, pages: int) -> None:
    path.write_bytes(_build_minimal_pdf(title=title, pages=pages))


def main() -> int:
    repo_root = Path(__file__).resolve().parents[1]
    out_dir = repo_root / "sample-input"
    out_dir.mkdir(parents=True, exist_ok=True)

    for doc in SAMPLE_DOCS:
        generate_pdf(out_dir / doc.filename, doc.title, doc.pages)

    print(f"Generated {len(SAMPLE_DOCS)} sample PDFs in: {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
